/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vng.luchm.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ActionUser implements org.apache.thrift.TEnum {
  PENDING(1),
  ACCEPTED(2),
  DECLINED(3),
  DELETED(4);

  private final int value;

  private ActionUser(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ActionUser findByValue(int value) { 
    switch (value) {
      case 1:
        return PENDING;
      case 2:
        return ACCEPTED;
      case 3:
        return DECLINED;
      case 4:
        return DELETED;
      default:
        return null;
    }
  }
}
